### ISSUE TITLE
Cubecell Configurator 8.1 can flash firmware button vanishing 

### ISSUE THREAD

**Issue by CMALG** [raystream/CubeCell_Getting_Started#1]
Hi,

with the new version 8.1 of the configrator i can't flash any firmware files.
When i press "Flash Firmware" button the complete box disappears and i have to restart the tool.

![button missing](https://user-images.githubusercontent.com/50234981/82146721-85ec1700-984c-11ea-9e6e-7bb25c4942ff.PNG)

**Comment by wasn-eu** [comment]
fixed that gui bug in the last commit https://github.com/wasn-eu/CubeCell_Getting_Started/commit/3f92c4a3ccc9160b07ee011f1f4f09a0a1e8623d
