### ISSUE TITLE
TTN Decoder not functioning for GPS only on cubecell Board

### ISSUE THREAD

**Issue by dafyddhirst** [raystream/CubeCell_Getting_Started#2]
If i have a cube cell board with a gps sensor only i get a payload of 
C8470552429F5455C00000000048C19643B0E69840AE47C94010BC01
with the decoder for TTN this is incorrect as i only get an incorrect battery level
"battery": 48129 
Version 3.1.1

**Comment by dafyddhirst** [comment]
Update on this. The 3.33, AGE: is incrementing so its not actually updating the data.
GPS is a neo6 MV2 powered via vext
26.07.20 06:32:32:   SATS: 4, HDOP: 6.29, LAT: 52.51, LON: -3.33, AGE: 377545, ALT: 0.00, COURSE: 301.51, SPEED: 4.78
.......
26.07.20 06:50:22:   SATS: 4, HDOP: 6.29, LAT: 52.51, LON: -3.33, AGE: 1447924, ALT: 0.00, COURSE: 301.51, SPEED: 4.78

**Comment by wasn-eu** [comment]
which cubecell board do you use and please post your wiring

**Comment by dafyddhirst** [comment]
Its a standard cubecell Board AB01
Neo 6 connected to GPIO 3/5 powered via vext and gnd

**Comment by wasn-eu** [comment]
How is you gps module configured?
It must send nmea sentences with 9600baud not the neo format

**Comment by wasn-eu** [comment]
No response
