### ISSUE TITLE
Cubecell firmware doesn't work with AU915

### ISSUE THREAD

**Issue by mbirrell66** [raystream/CubeCell_Getting_Started#3]
Hi after flashing with WASN CubeCell Configurator, my CubeCell does not transmit packets to my gateway. When I use Arduino IDE with CubeCell Development Framework with version 0.0.3 installed (later versions don't seem to work) my CubeCell connects to my gateway and joins the TTN. I would like to use the CubeCell Configurator as is a much simpler way to configure my sensors. Any help would be appreciated.

**Comment by wasn-eu** [comment]
sorry for replying so late.
i dont have a 915MHz gateway only one for 868MHz.
Cant test the other frequencies here
