### ISSUE TITLE
Heltec AB01 and Chirpstack

### ISSUE THREAD

**Issue by rmperreault** [raystream/CubeCell_Getting_Started#5]
Hi, i used the configurator to load the US915 Board firmware.  I am also able to join Chirpstack, decode the payload and send data via MQTT.  I do receive all transmission via my Kona Lite gateway but the problem starts when the transmission switches from fport 2 (AppPort) which works fine showing all data to fport 0 which still receive the transmission without errors on Chirpstack but it shows data being null (no data).  
It consistently switches the port after the 4th count.  How do i fix this issue - heltec firmware? Chirpstack setting? or a gateway issue?

Thanks for your assistance

**Comment by wasn-eu** [comment]
i cant test for other frerquencies than 868MHz here in Europe.
In the 868MHz band that does not happen
