### ISSUE TITLE
Payload formatters error TTN V3 

### ISSUE THREAD

**Issue by b2techgeek** [raystream/CubeCell_Getting_Started#6]
hello
i have an error message with ttn console v3 with the payload formatters.
I use [CubeCell Capsule Solar Sensor] with CCS811B sensor
I used the file given on github at this address: CubeCell_Getting_Started/ttn-decode.js at master · wasn-eu/CubeCell_Getting_Started · GitHub
can you help me?
thank you in advance.

error message:

Invalid end_device: embedded message failed validation

arrow_drop_upHide details
{
  "code": 3,
  "message": "error:pkg/errors:validation (invalid `end_device`: embedded message failed validation)",
  "details": [
    {
      "@type": "type.googleapis.com/ttn.lorawan.v3.ErrorDetails",
      "namespace": "pkg/errors",
      "name": "validation",
      "message_format": "invalid `{field}`: {reason}",
      "attributes": {
        "field": "end_device",
        "name": "SetEndDeviceRequestValidationError",
        "reason": "embedded message failed validation"
      },
      "correlation_id": "947c6ecc82604f219081a57224927f06",
      "cause": {
        "namespace": "pkg/errors",
        "name": "validation",
        "message_format": "invalid `{field}`: {reason}",
        "attributes": {
          "field": "formatters",
          "name": "EndDeviceValidationError",
          "reason": "embedded message failed validation"
        },
        "cause": {
          "namespace": "pkg/errors",
          "name": "validation",
          "message_format": "invalid `{field}`: {reason}",
          "attributes": {
            "field": "up_formatter_parameter",
            "name": "MessagePayloadFormattersValidationError",
            "reason": "value length must be at most 16384 runes"
          },
          "code": 3
        },
        "code": 3
      },
      "code": 3
    }
  ],
  "request_details": {
    "url": "/as/applications/capsule-air/devices/capsule-air",
    "method": "put",
    "stack_component": "as"
  }
}

**Comment by b2techgeek** [comment]
![Capture](https://user-images.githubusercontent.com/83314523/122642632-b109ff80-d10b-11eb-9f94-33a94f668b15.JPG)

**Comment by sivaelid** [comment]
I Agree get the same responce the Code is failing the Validation process

**Comment by wasn-eu** [comment]
just updated the ttn decoder file.
this version is working for me since the v3 console has started.

**Comment by b2techgeek** [comment]
> I Agree get the same responce the Code is failing the Validation process

the solution below:
[https://www.zupimages.net/up/21/28/kgas.jpg](url)
