### ISSUE TITLE
SHT2X Library invalid value for temperature

### ISSUE THREAD

**Issue by conrad784** [raystream/CubeCell_Getting_Started#7]
Hi, first of all I am loving your project, I did not succeed that my own firmware was able to talk to TTN v3 until now...

Using your software was successful, but exhibited some other quirks. I am using a Cubecell Dev Board.
Connecting a Si7021 (SHT21 + HTU21) results in the right humidity signal but in -237° (in ttn then 6281).
In contrast to a BMP280 (which I had lying around) which only shows invalid values right after the start, the temperature value of the Si7021 stays like this forever (multiple days).
Using the sensor with the Adafruit_Si7021.h library on other boards did result in correct values.

Btw, are you planning in releasing the source code for the Cubecell Boards?

**Comment by wasn-eu** [comment]
you can find a little older version in the official repository of heltec under examples

dont have a Si7021 here tom test

**Comment by ken016** [comment]
Hello, i use a SHT20 and has no correct resaults.   Under TTN: Payload P0_SHT2X_humidity 0 P0_SHT2X_temperature 6280.6
How can i fix?

and many thanks for this project :-)

**Comment by wasn-eu** [comment]
you can find a little older version of the source code in the official repository of heltec under examples

dont have a SHT20 here to test.

Just download the source code and try an other library for the SHT20
