### ISSUE TITLE
Invalid GPS locations reported by Cubecell

### ISSUE THREAD

**Issue by jpmeijers** [raystream/CubeCell_Getting_Started#8]
Reporting this issue here as TTN Mapper is mentioned in the readme, and some users might be using it for mapping. I'm not sure where the issue comes from, but maybe someone following this repo knows.

On TTN Mapper a pattern is appearing where Cubecell trackers regularly report invalid coordinates - often in the Gulf of Guinea. This messes up the global coverage map, and requires a lot of effort to clean up.

Full description here:
https://github.com/Bwooce/CubeCellTTNMapper/issues/2

**Comment by wasn-eu** [comment]
the Mapper firmware is not supported anymore.
it was only a try.
this failure is happening when there is no GPS signal and this is not filtered out of the sended signals.
